name: projetoeolico
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+5
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  get_it: ^7.2.0
  file_picker: ^4.5.1
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Bold.ttf
        - asset: fonts/Inter/Inter-Regular.ttf
  uses-material-design: true